### PR TITLE
fix: close any open dropdown or related components with overlay clicks

### LINKED ISSUE #40: dropdown in dialog: when clicking outside of dialog while dropdown open, the entire dialog closes
### Please verify the version of auro-form you have installed

1.5.0

### Please describe the bug

1. open a dialog 
2. open a dropdown
3. click anywhere outside of dialog

### Reproducing the error

None

### Expected behavior

only dropdown closes

### What browsers are you seeing the problem on?

_No response_

### Additional context

Is this correct behavior? 

### Exit criteria

_No response_

### PR DESCRIPTION
**Pull request by sun-mota**
# Alaska Airlines Pull Request

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

**Resolves:** #40

## Summary:

Clicking overlay will not close the dialog when there is an open dropdown

_Please summarize the scope of the changes you have submitted, what the intent of the work is and anything that describes the before/after state of the project._

## Type of change:

Please delete options that are not relevant.

- [ ] New capability
- [x] Revision of an existing capability
- [ ] Infrastructure change (automation, etc.)
- [ ] Other (please elaborate)

## Checklist:

- [x] My update follows the CONTRIBUTING guidelines of this project
- [x] I have performed a self-review of my own update

**By submitting this Pull Request, I confirm that my contribution is made under the terms of the Apache 2.0 license.**

_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require changes to your submission._

**Thank you for your submission!**<br>
-- Auro Design System Team

### CODE REVIEW

File: src/componentBase.js [hunk 1]
```diff
@@ -197,7 +197,16 @@ export default class ComponentBase extends LitElement {
    */
   handleOverlayClick() {
     if (this.open && !this.modal) {
-      this.handleCloseButtonClick();
+      const dropdownComponents = [...this.querySelectorAll('auro-combobox, [auro-combobox], auro-select, [auro-select]')];
```
Comment (jordanjones243) [inline src/componentBase.js]: This should also include auro-datepicker

**Review by jordanjones243 — CHANGES_REQUESTED** [review]

**Review by jordanjones243 — APPROVED** [review]
